<a href="https://colab.research.google.com/github/Ambigapathi-V/Learnings/blob/main/Linear_Regression_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [32]:
df=pd.read_csv("/content/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
df.rename(columns={'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score','salary($)':'salary'},inplace=True)

In [34]:
df.dtypes

experience          object
test_score         float64
interview_score      int64
salary               int64
dtype: object

In [35]:
df.dtypes

experience          object
test_score         float64
interview_score      int64
salary               int64
dtype: object

In [36]:
import math
med_testscore=math.floor(df.test_score.median())
med_testscore

8

In [37]:
df['test_score']=df['test_score'].fillna(med_testscore).astype('int')
df

experience  test_score  interview_score  salary
0        NaN           8                9   50000
1        NaN           8                6   45000
2       five           6                7   60000
3        two          10               10   65000
4      seven           9                6   70000
5      three           7               10   62000
6        ten           8                7   72000
7     eleven           7                8   80000

In [40]:
df['experience']=df['experience'].fillna('zero')
df

experience  test_score  interview_score  salary
0       zero           8                9   50000
1       zero           8                6   45000
2       five           6                7   60000
3        two          10               10   65000
4      seven           9                6   70000
5      three           7               10   62000
6        ten           8                7   72000
7     eleven           7                8   80000

In [51]:
from word2number import w2n

In [54]:
df.experience=df.experience.astype(str)
df.experience= df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0           8                9   50000
1           0           8                6   45000
2           5           6                7   60000
3           2          10               10   65000
4           7           9                6   70000
5           3           7               10   62000
6          10           8                7   72000
7          11           7                8   80000

In [55]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [56]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [57]:
reg.intercept_

17737.263464337688

In [58]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8550348.61717613])

In [59]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [60]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])